'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WorkSpace.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AcadDWGAssoc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AcadDWGAssoc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Foil_Thunder_beta_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Foil Thunder beta 5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FoilThunder_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FoilThunder-Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sealant And Backer Rod Not By Northshore
        '''Wrb Not By Northshore
        '''Foil Faced S.A.M. Not By Northshore
        '''Wood And Woodworking Not By Northshore
        '''Roofing Not By Northshore
        '''
        '''24 Gauge Zinc-Alum Flashing, Pre Finished Standard Color
        '''24 Gauge Zinc-Alum Flashing, Pre Finished Standard Color To Match Wall Panel
        '''24 gauge Bare Galv. Cleat
        '''1&quot; Standing Seam Coping Joint @ 9&apos;-10&quot; O.C.
        '''Flashing Set Into Continuous Sealant
        '''
        '''EDPM Washered Galv. SMS Screws @ 24&quot; O.C. Max
        '''Galv. SMS Screws @ 24&quot; O.C. Max
        '''EDPM Washered [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Standard() As String
            Get
                Return ResourceManager.GetString("Standard", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
